exec --no-startup-id dex --autostart --environment i3
exec --no-startup-id xss-lock --transfer-sleep-lock -- betterlockscreen --lock dimblur
exec --no-startup-id xsettingsd --config=~/.config/xsettingsd/xsettingsd.conf
# feh --bg-fill /usr/share/backgrounds/minimalistic/ellysiumn-flaming-kingdom.jpg
exec --no-startup-id sleep 1 && feh --bg-fill /usr/share/backgrounds/minimalistic/josef-barton-the-last-one.jpg /usr/share/backgrounds/minimalistic/ellysiumn-flaming-kingdom.jpg
exec --no-startup-id picom --experimental-backends --config ~/.config/picom/picom.conf
exec_always --no-startup-id ~/.config/polybar/scripts/polybar_launcher.sh
exec --no-startup-id nm-applet
exec --no-startup-id dunst
exec_always --no-startup-id xsettingsd
exec_always --no-startup-id blueberry-tray


# set desktop background with custom effect
exec --no-startup-id betterlockscreen -w dim

# Alternative (set last used background)
# exec --no-startup-id source ~/.fehbg

exec --no-startup-id feh --bg-fill '/usr/share/backgrounds/minimalistic/bisbiswas-verdant-moonlight-no-people-edit.jpg' '/usr/share/backgrounds/minimalistic/gustavo-arteaga-revenge.jpg' 
