# ── Everforest Dark (medium) ──────────────────────────────
set $black              #232a2e
set $white              #FFFFFF
set $background         #2d353b
set $background_alt     #343f44
set $foreground         #d3c6aa
set $primary            #a7c080
set $primary50          #a7c08060
set $primaryLight       #83c092
set $red                #e67e80
set $cream              #d3c6aa
set $green              #a7c080
set $green-alt          #83c092
set $transparent        #00000000

# define colors for windows:
#class                    border            bground           text          indicator       child_border
client.focused            $primary          $background       $foreground   $primaryLight   $primary
client.unfocused          $background_alt   $background       $foreground   $background_alt $background_alt
client.focused_inactive   $background_alt   $background       $foreground   $background_alt $background_alt
client.urgent             $red              $red              $background   $red            $red
